name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install --prefix functions

      - name: Build Firebase Functions
        run: npm run build --prefix functions  # Adjust build script as per your project setup

      - name: Archive Firebase Functions
        uses: actions/upload-artifact@v2
        with:
          name: functions-artifact
          path: functions  # Path to the Firebase functions directory or build output directory

      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only functions --token "$FIREBASE_TOKEN"
