name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust Node.js version as needed

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install --prefix functions

      - name: Build Firebase Functions
        run: npm run build --prefix functions  # Run the build script defined in package.json

      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        run: |
          cd functions
          firebase deploy --only functions --token "$GOOGLE_APPLICATION_CREDENTIALS"
