name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install --prefix functions

      - name: Build Firebase Functions
        run: npm run build --prefix functions

      - name: Decode Service Account Key
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > /tmp/service-account-key.json

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project=dyanamicwebsites --service-account=/tmp/service-account-key.json
