name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --prefix functions


      - name: Run tests
        run: |
          # Add your test commands here if you have tests
          echo "No tests configured"

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd functions
          npm run deploy

